USERMODULES_DIR := $(USERMOD_DIR)/src

# Add all C files to SRC_USERMOD.
SRC_USERMOD += $(USERMODULES_DIR)/ndarray.c
SRC_USERMOD += $(USERMODULES_DIR)/binary.c
SRC_USERMOD += $(USERMODULES_DIR)/unary.c
SRC_USERMOD += $(USERMODULES_DIR)/slice.c
SRC_USERMOD += $(USERMODULES_DIR)/array.c
SRC_USERMOD += $(USERMODULES_DIR)/scalar.c
SRC_USERMOD += $(USERMODULES_DIR)/array2d.c

SRC_USERMOD += $(USERMODULES_DIR)/numpy.c

CFLAGS_USERMOD += -I$(USERMODULES_DIR)
